//go:build windows || linux

package nvapi

import "fmt"

// CUresult represents CUDA Driver API return status codes.
type CUresult uint32

const (
	CUDA_SUCCESS CUresult = 0
	CUDA_ERROR_INVALID_VALUE CUresult = 1
	CUDA_ERROR_OUT_OF_MEMORY CUresult = 2
	CUDA_ERROR_NOT_INITIALIZED CUresult = 3
	CUDA_ERROR_DEINITIALIZED CUresult = 4
	CUDA_ERROR_PROFILER_DISABLED CUresult = 5
	CUDA_ERROR_PROFILER_NOT_INITIALIZED CUresult = 6
	CUDA_ERROR_PROFILER_ALREADY_STARTED CUresult = 7
	CUDA_ERROR_PROFILER_ALREADY_STOPPED CUresult = 8
	CUDA_ERROR_STUB_LIBRARY CUresult = 34
	CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER CUresult = 36
	CUDA_ERROR_DEVICE_UNAVAILABLE CUresult = 46
	CUDA_ERROR_NO_DEVICE CUresult = 100
	CUDA_ERROR_INVALID_DEVICE CUresult = 101
	CUDA_ERROR_DEVICE_NOT_LICENSED CUresult = 102
	CUDA_ERROR_INVALID_IMAGE CUresult = 200
	CUDA_ERROR_INVALID_CONTEXT CUresult = 201
	CUDA_ERROR_CONTEXT_ALREADY_CURRENT CUresult = 202
	CUDA_ERROR_MAP_FAILED CUresult = 205
	CUDA_ERROR_UNMAP_FAILED CUresult = 206
	CUDA_ERROR_ARRAY_IS_MAPPED CUresult = 207
	CUDA_ERROR_ALREADY_MAPPED CUresult = 208
	CUDA_ERROR_NO_BINARY_FOR_GPU CUresult = 209
	CUDA_ERROR_ALREADY_ACQUIRED CUresult = 210
	CUDA_ERROR_NOT_MAPPED CUresult = 211
	CUDA_ERROR_NOT_MAPPED_AS_ARRAY CUresult = 212
	CUDA_ERROR_NOT_MAPPED_AS_POINTER CUresult = 213
	CUDA_ERROR_ECC_UNCORRECTABLE CUresult = 214
	CUDA_ERROR_UNSUPPORTED_LIMIT CUresult = 215
	CUDA_ERROR_CONTEXT_ALREADY_IN_USE CUresult = 216
	CUDA_ERROR_PEER_ACCESS_UNSUPPORTED CUresult = 217
	CUDA_ERROR_INVALID_PTX CUresult = 218
	CUDA_ERROR_INVALID_GRAPHICS_CONTEXT CUresult = 219
	CUDA_ERROR_NVLINK_UNCORRECTABLE CUresult = 220
	CUDA_ERROR_JIT_COMPILER_NOT_FOUND CUresult = 221
	CUDA_ERROR_UNSUPPORTED_PTX_VERSION CUresult = 222
	CUDA_ERROR_JIT_COMPILATION_DISABLED CUresult = 223
	CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY CUresult = 224
	CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC CUresult = 225
	CUDA_ERROR_CONTAINED CUresult = 226
	CUDA_ERROR_INVALID_SOURCE CUresult = 300
	CUDA_ERROR_FILE_NOT_FOUND CUresult = 301
	CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND CUresult = 302
	CUDA_ERROR_SHARED_OBJECT_INIT_FAILED CUresult = 303
	CUDA_ERROR_OPERATING_SYSTEM CUresult = 304
	CUDA_ERROR_INVALID_HANDLE CUresult = 400
	CUDA_ERROR_ILLEGAL_STATE CUresult = 401
	CUDA_ERROR_LOSSY_QUERY CUresult = 402
	CUDA_ERROR_NOT_FOUND CUresult = 500
	CUDA_ERROR_NOT_READY CUresult = 600
	CUDA_ERROR_ILLEGAL_ADDRESS CUresult = 700
	CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES CUresult = 701
	CUDA_ERROR_LAUNCH_TIMEOUT CUresult = 702
	CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING CUresult = 703
	CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED CUresult = 704
	CUDA_ERROR_PEER_ACCESS_NOT_ENABLED CUresult = 705
	CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE CUresult = 708
	CUDA_ERROR_CONTEXT_IS_DESTROYED CUresult = 709
	CUDA_ERROR_ASSERT CUresult = 710
	CUDA_ERROR_TOO_MANY_PEERS CUresult = 711
	CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED CUresult = 712
	CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED CUresult = 713
	CUDA_ERROR_HARDWARE_STACK_ERROR CUresult = 714
	CUDA_ERROR_ILLEGAL_INSTRUCTION CUresult = 715
	CUDA_ERROR_MISALIGNED_ADDRESS CUresult = 716
	CUDA_ERROR_INVALID_ADDRESS_SPACE CUresult = 717
	CUDA_ERROR_INVALID_PC CUresult = 718
	CUDA_ERROR_LAUNCH_FAILED CUresult = 719
	CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE CUresult = 720
	CUDA_ERROR_TENSOR_MEMORY_LEAK CUresult = 721
	CUDA_ERROR_NOT_PERMITTED CUresult = 800
	CUDA_ERROR_NOT_SUPPORTED CUresult = 801
	CUDA_ERROR_SYSTEM_NOT_READY CUresult = 802
	CUDA_ERROR_SYSTEM_DRIVER_MISMATCH CUresult = 803
	CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE CUresult = 804
	CUDA_ERROR_MPS_CONNECTION_FAILED CUresult = 805
	CUDA_ERROR_MPS_RPC_FAILURE CUresult = 806
	CUDA_ERROR_MPS_SERVER_NOT_READY CUresult = 807
	CUDA_ERROR_MPS_MAX_CLIENTS_REACHED CUresult = 808
	CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED CUresult = 809
	CUDA_ERROR_MPS_CLIENT_TERMINATED CUresult = 810
	CUDA_ERROR_CDP_NOT_SUPPORTED CUresult = 811
	CUDA_ERROR_CDP_VERSION_MISMATCH CUresult = 812
	CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED CUresult = 900
	CUDA_ERROR_STREAM_CAPTURE_INVALIDATED CUresult = 901
	CUDA_ERROR_STREAM_CAPTURE_MERGE CUresult = 902
	CUDA_ERROR_STREAM_CAPTURE_UNMATCHED CUresult = 903
	CUDA_ERROR_STREAM_CAPTURE_UNJOINED CUresult = 904
	CUDA_ERROR_STREAM_CAPTURE_ISOLATION CUresult = 905
	CUDA_ERROR_STREAM_CAPTURE_IMPLICIT CUresult = 906
	CUDA_ERROR_CAPTURED_EVENT CUresult = 907
	CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD CUresult = 908
	CUDA_ERROR_TIMEOUT CUresult = 909
	CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE CUresult = 910
	CUDA_ERROR_EXTERNAL_DEVICE CUresult = 911
	CUDA_ERROR_INVALID_CLUSTER_SIZE CUresult = 912
	CUDA_ERROR_FUNCTION_NOT_LOADED CUresult = 913
	CUDA_ERROR_INVALID_RESOURCE_TYPE CUresult = 914
	CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION CUresult = 915
	CUDA_ERROR_KEY_ROTATION CUresult = 916
	CUDA_ERROR_UNKNOWN CUresult = 999
)

// Error implements the error interface for CUresult.
func (r CUresult) Error() string {
	switch r {
	case CUDA_SUCCESS:
		return "CUDA_SUCCESS: CUDA_SUCCESS"
	case CUDA_ERROR_INVALID_VALUE:
		return "CUDA_ERROR_INVALID_VALUE: CUDA_ERROR_INVALID_VALUE"
	case CUDA_ERROR_OUT_OF_MEMORY:
		return "CUDA_ERROR_OUT_OF_MEMORY: CUDA_ERROR_OUT_OF_MEMORY"
	case CUDA_ERROR_NOT_INITIALIZED:
		return "CUDA_ERROR_NOT_INITIALIZED: CUDA_ERROR_NOT_INITIALIZED"
	case CUDA_ERROR_DEINITIALIZED:
		return "CUDA_ERROR_DEINITIALIZED: CUDA_ERROR_DEINITIALIZED"
	case CUDA_ERROR_PROFILER_DISABLED:
		return "CUDA_ERROR_PROFILER_DISABLED: CUDA_ERROR_PROFILER_DISABLED"
	case CUDA_ERROR_PROFILER_NOT_INITIALIZED:
		return "CUDA_ERROR_PROFILER_NOT_INITIALIZED: CUDA_ERROR_PROFILER_NOT_INITIALIZED"
	case CUDA_ERROR_PROFILER_ALREADY_STARTED:
		return "CUDA_ERROR_PROFILER_ALREADY_STARTED: CUDA_ERROR_PROFILER_ALREADY_STARTED"
	case CUDA_ERROR_PROFILER_ALREADY_STOPPED:
		return "CUDA_ERROR_PROFILER_ALREADY_STOPPED: CUDA_ERROR_PROFILER_ALREADY_STOPPED"
	case CUDA_ERROR_STUB_LIBRARY:
		return "CUDA_ERROR_STUB_LIBRARY: CUDA_ERROR_STUB_LIBRARY"
	case CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER:
		return "CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER: CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER"
	case CUDA_ERROR_DEVICE_UNAVAILABLE:
		return "CUDA_ERROR_DEVICE_UNAVAILABLE: CUDA_ERROR_DEVICE_UNAVAILABLE"
	case CUDA_ERROR_NO_DEVICE:
		return "CUDA_ERROR_NO_DEVICE: CUDA_ERROR_NO_DEVICE"
	case CUDA_ERROR_INVALID_DEVICE:
		return "CUDA_ERROR_INVALID_DEVICE: CUDA_ERROR_INVALID_DEVICE"
	case CUDA_ERROR_DEVICE_NOT_LICENSED:
		return "CUDA_ERROR_DEVICE_NOT_LICENSED: CUDA_ERROR_DEVICE_NOT_LICENSED"
	case CUDA_ERROR_INVALID_IMAGE:
		return "CUDA_ERROR_INVALID_IMAGE: CUDA_ERROR_INVALID_IMAGE"
	case CUDA_ERROR_INVALID_CONTEXT:
		return "CUDA_ERROR_INVALID_CONTEXT: CUDA_ERROR_INVALID_CONTEXT"
	case CUDA_ERROR_CONTEXT_ALREADY_CURRENT:
		return "CUDA_ERROR_CONTEXT_ALREADY_CURRENT: CUDA_ERROR_CONTEXT_ALREADY_CURRENT"
	case CUDA_ERROR_MAP_FAILED:
		return "CUDA_ERROR_MAP_FAILED: CUDA_ERROR_MAP_FAILED"
	case CUDA_ERROR_UNMAP_FAILED:
		return "CUDA_ERROR_UNMAP_FAILED: CUDA_ERROR_UNMAP_FAILED"
	case CUDA_ERROR_ARRAY_IS_MAPPED:
		return "CUDA_ERROR_ARRAY_IS_MAPPED: CUDA_ERROR_ARRAY_IS_MAPPED"
	case CUDA_ERROR_ALREADY_MAPPED:
		return "CUDA_ERROR_ALREADY_MAPPED: CUDA_ERROR_ALREADY_MAPPED"
	case CUDA_ERROR_NO_BINARY_FOR_GPU:
		return "CUDA_ERROR_NO_BINARY_FOR_GPU: CUDA_ERROR_NO_BINARY_FOR_GPU"
	case CUDA_ERROR_ALREADY_ACQUIRED:
		return "CUDA_ERROR_ALREADY_ACQUIRED: CUDA_ERROR_ALREADY_ACQUIRED"
	case CUDA_ERROR_NOT_MAPPED:
		return "CUDA_ERROR_NOT_MAPPED: CUDA_ERROR_NOT_MAPPED"
	case CUDA_ERROR_NOT_MAPPED_AS_ARRAY:
		return "CUDA_ERROR_NOT_MAPPED_AS_ARRAY: CUDA_ERROR_NOT_MAPPED_AS_ARRAY"
	case CUDA_ERROR_NOT_MAPPED_AS_POINTER:
		return "CUDA_ERROR_NOT_MAPPED_AS_POINTER: CUDA_ERROR_NOT_MAPPED_AS_POINTER"
	case CUDA_ERROR_ECC_UNCORRECTABLE:
		return "CUDA_ERROR_ECC_UNCORRECTABLE: CUDA_ERROR_ECC_UNCORRECTABLE"
	case CUDA_ERROR_UNSUPPORTED_LIMIT:
		return "CUDA_ERROR_UNSUPPORTED_LIMIT: CUDA_ERROR_UNSUPPORTED_LIMIT"
	case CUDA_ERROR_CONTEXT_ALREADY_IN_USE:
		return "CUDA_ERROR_CONTEXT_ALREADY_IN_USE: CUDA_ERROR_CONTEXT_ALREADY_IN_USE"
	case CUDA_ERROR_PEER_ACCESS_UNSUPPORTED:
		return "CUDA_ERROR_PEER_ACCESS_UNSUPPORTED: CUDA_ERROR_PEER_ACCESS_UNSUPPORTED"
	case CUDA_ERROR_INVALID_PTX:
		return "CUDA_ERROR_INVALID_PTX: CUDA_ERROR_INVALID_PTX"
	case CUDA_ERROR_INVALID_GRAPHICS_CONTEXT:
		return "CUDA_ERROR_INVALID_GRAPHICS_CONTEXT: CUDA_ERROR_INVALID_GRAPHICS_CONTEXT"
	case CUDA_ERROR_NVLINK_UNCORRECTABLE:
		return "CUDA_ERROR_NVLINK_UNCORRECTABLE: CUDA_ERROR_NVLINK_UNCORRECTABLE"
	case CUDA_ERROR_JIT_COMPILER_NOT_FOUND:
		return "CUDA_ERROR_JIT_COMPILER_NOT_FOUND: CUDA_ERROR_JIT_COMPILER_NOT_FOUND"
	case CUDA_ERROR_UNSUPPORTED_PTX_VERSION:
		return "CUDA_ERROR_UNSUPPORTED_PTX_VERSION: CUDA_ERROR_UNSUPPORTED_PTX_VERSION"
	case CUDA_ERROR_JIT_COMPILATION_DISABLED:
		return "CUDA_ERROR_JIT_COMPILATION_DISABLED: CUDA_ERROR_JIT_COMPILATION_DISABLED"
	case CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY:
		return "CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY: CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY"
	case CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC:
		return "CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC: CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC"
	case CUDA_ERROR_CONTAINED:
		return "CUDA_ERROR_CONTAINED: CUDA_ERROR_CONTAINED"
	case CUDA_ERROR_INVALID_SOURCE:
		return "CUDA_ERROR_INVALID_SOURCE: CUDA_ERROR_INVALID_SOURCE"
	case CUDA_ERROR_FILE_NOT_FOUND:
		return "CUDA_ERROR_FILE_NOT_FOUND: CUDA_ERROR_FILE_NOT_FOUND"
	case CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND:
		return "CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND: CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND"
	case CUDA_ERROR_SHARED_OBJECT_INIT_FAILED:
		return "CUDA_ERROR_SHARED_OBJECT_INIT_FAILED: CUDA_ERROR_SHARED_OBJECT_INIT_FAILED"
	case CUDA_ERROR_OPERATING_SYSTEM:
		return "CUDA_ERROR_OPERATING_SYSTEM: CUDA_ERROR_OPERATING_SYSTEM"
	case CUDA_ERROR_INVALID_HANDLE:
		return "CUDA_ERROR_INVALID_HANDLE: CUDA_ERROR_INVALID_HANDLE"
	case CUDA_ERROR_ILLEGAL_STATE:
		return "CUDA_ERROR_ILLEGAL_STATE: CUDA_ERROR_ILLEGAL_STATE"
	case CUDA_ERROR_LOSSY_QUERY:
		return "CUDA_ERROR_LOSSY_QUERY: CUDA_ERROR_LOSSY_QUERY"
	case CUDA_ERROR_NOT_FOUND:
		return "CUDA_ERROR_NOT_FOUND: CUDA_ERROR_NOT_FOUND"
	case CUDA_ERROR_NOT_READY:
		return "CUDA_ERROR_NOT_READY: CUDA_ERROR_NOT_READY"
	case CUDA_ERROR_ILLEGAL_ADDRESS:
		return "CUDA_ERROR_ILLEGAL_ADDRESS: CUDA_ERROR_ILLEGAL_ADDRESS"
	case CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES:
		return "CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES: CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES"
	case CUDA_ERROR_LAUNCH_TIMEOUT:
		return "CUDA_ERROR_LAUNCH_TIMEOUT: CUDA_ERROR_LAUNCH_TIMEOUT"
	case CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING:
		return "CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING: CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING"
	case CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED:
		return "CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED: CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED"
	case CUDA_ERROR_PEER_ACCESS_NOT_ENABLED:
		return "CUDA_ERROR_PEER_ACCESS_NOT_ENABLED: CUDA_ERROR_PEER_ACCESS_NOT_ENABLED"
	case CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE:
		return "CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE: CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE"
	case CUDA_ERROR_CONTEXT_IS_DESTROYED:
		return "CUDA_ERROR_CONTEXT_IS_DESTROYED: CUDA_ERROR_CONTEXT_IS_DESTROYED"
	case CUDA_ERROR_ASSERT:
		return "CUDA_ERROR_ASSERT: CUDA_ERROR_ASSERT"
	case CUDA_ERROR_TOO_MANY_PEERS:
		return "CUDA_ERROR_TOO_MANY_PEERS: CUDA_ERROR_TOO_MANY_PEERS"
	case CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED:
		return "CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED: CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED"
	case CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED:
		return "CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED: CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED"
	case CUDA_ERROR_HARDWARE_STACK_ERROR:
		return "CUDA_ERROR_HARDWARE_STACK_ERROR: CUDA_ERROR_HARDWARE_STACK_ERROR"
	case CUDA_ERROR_ILLEGAL_INSTRUCTION:
		return "CUDA_ERROR_ILLEGAL_INSTRUCTION: CUDA_ERROR_ILLEGAL_INSTRUCTION"
	case CUDA_ERROR_MISALIGNED_ADDRESS:
		return "CUDA_ERROR_MISALIGNED_ADDRESS: CUDA_ERROR_MISALIGNED_ADDRESS"
	case CUDA_ERROR_INVALID_ADDRESS_SPACE:
		return "CUDA_ERROR_INVALID_ADDRESS_SPACE: CUDA_ERROR_INVALID_ADDRESS_SPACE"
	case CUDA_ERROR_INVALID_PC:
		return "CUDA_ERROR_INVALID_PC: CUDA_ERROR_INVALID_PC"
	case CUDA_ERROR_LAUNCH_FAILED:
		return "CUDA_ERROR_LAUNCH_FAILED: CUDA_ERROR_LAUNCH_FAILED"
	case CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE:
		return "CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE: CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE"
	case CUDA_ERROR_TENSOR_MEMORY_LEAK:
		return "CUDA_ERROR_TENSOR_MEMORY_LEAK: CUDA_ERROR_TENSOR_MEMORY_LEAK"
	case CUDA_ERROR_NOT_PERMITTED:
		return "CUDA_ERROR_NOT_PERMITTED: CUDA_ERROR_NOT_PERMITTED"
	case CUDA_ERROR_NOT_SUPPORTED:
		return "CUDA_ERROR_NOT_SUPPORTED: CUDA_ERROR_NOT_SUPPORTED"
	case CUDA_ERROR_SYSTEM_NOT_READY:
		return "CUDA_ERROR_SYSTEM_NOT_READY: CUDA_ERROR_SYSTEM_NOT_READY"
	case CUDA_ERROR_SYSTEM_DRIVER_MISMATCH:
		return "CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH"
	case CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE:
		return "CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE"
	case CUDA_ERROR_MPS_CONNECTION_FAILED:
		return "CUDA_ERROR_MPS_CONNECTION_FAILED: CUDA_ERROR_MPS_CONNECTION_FAILED"
	case CUDA_ERROR_MPS_RPC_FAILURE:
		return "CUDA_ERROR_MPS_RPC_FAILURE: CUDA_ERROR_MPS_RPC_FAILURE"
	case CUDA_ERROR_MPS_SERVER_NOT_READY:
		return "CUDA_ERROR_MPS_SERVER_NOT_READY: CUDA_ERROR_MPS_SERVER_NOT_READY"
	case CUDA_ERROR_MPS_MAX_CLIENTS_REACHED:
		return "CUDA_ERROR_MPS_MAX_CLIENTS_REACHED: CUDA_ERROR_MPS_MAX_CLIENTS_REACHED"
	case CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED:
		return "CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED: CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED"
	case CUDA_ERROR_MPS_CLIENT_TERMINATED:
		return "CUDA_ERROR_MPS_CLIENT_TERMINATED: CUDA_ERROR_MPS_CLIENT_TERMINATED"
	case CUDA_ERROR_CDP_NOT_SUPPORTED:
		return "CUDA_ERROR_CDP_NOT_SUPPORTED: CUDA_ERROR_CDP_NOT_SUPPORTED"
	case CUDA_ERROR_CDP_VERSION_MISMATCH:
		return "CUDA_ERROR_CDP_VERSION_MISMATCH: CUDA_ERROR_CDP_VERSION_MISMATCH"
	case CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED:
		return "CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED: CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED"
	case CUDA_ERROR_STREAM_CAPTURE_INVALIDATED:
		return "CUDA_ERROR_STREAM_CAPTURE_INVALIDATED: CUDA_ERROR_STREAM_CAPTURE_INVALIDATED"
	case CUDA_ERROR_STREAM_CAPTURE_MERGE:
		return "CUDA_ERROR_STREAM_CAPTURE_MERGE: CUDA_ERROR_STREAM_CAPTURE_MERGE"
	case CUDA_ERROR_STREAM_CAPTURE_UNMATCHED:
		return "CUDA_ERROR_STREAM_CAPTURE_UNMATCHED: CUDA_ERROR_STREAM_CAPTURE_UNMATCHED"
	case CUDA_ERROR_STREAM_CAPTURE_UNJOINED:
		return "CUDA_ERROR_STREAM_CAPTURE_UNJOINED: CUDA_ERROR_STREAM_CAPTURE_UNJOINED"
	case CUDA_ERROR_STREAM_CAPTURE_ISOLATION:
		return "CUDA_ERROR_STREAM_CAPTURE_ISOLATION: CUDA_ERROR_STREAM_CAPTURE_ISOLATION"
	case CUDA_ERROR_STREAM_CAPTURE_IMPLICIT:
		return "CUDA_ERROR_STREAM_CAPTURE_IMPLICIT: CUDA_ERROR_STREAM_CAPTURE_IMPLICIT"
	case CUDA_ERROR_CAPTURED_EVENT:
		return "CUDA_ERROR_CAPTURED_EVENT: CUDA_ERROR_CAPTURED_EVENT"
	case CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD:
		return "CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD: CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD"
	case CUDA_ERROR_TIMEOUT:
		return "CUDA_ERROR_TIMEOUT: CUDA_ERROR_TIMEOUT"
	case CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE:
		return "CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE: CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE"
	case CUDA_ERROR_EXTERNAL_DEVICE:
		return "CUDA_ERROR_EXTERNAL_DEVICE: CUDA_ERROR_EXTERNAL_DEVICE"
	case CUDA_ERROR_INVALID_CLUSTER_SIZE:
		return "CUDA_ERROR_INVALID_CLUSTER_SIZE: CUDA_ERROR_INVALID_CLUSTER_SIZE"
	case CUDA_ERROR_FUNCTION_NOT_LOADED:
		return "CUDA_ERROR_FUNCTION_NOT_LOADED: CUDA_ERROR_FUNCTION_NOT_LOADED"
	case CUDA_ERROR_INVALID_RESOURCE_TYPE:
		return "CUDA_ERROR_INVALID_RESOURCE_TYPE: CUDA_ERROR_INVALID_RESOURCE_TYPE"
	case CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION:
		return "CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION: CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION"
	case CUDA_ERROR_KEY_ROTATION:
		return "CUDA_ERROR_KEY_ROTATION: CUDA_ERROR_KEY_ROTATION"
	case CUDA_ERROR_UNKNOWN:
		return "CUDA_ERROR_UNKNOWN: CUDA_ERROR_UNKNOWN"
	default:
		return fmt.Sprintf("CUDA_ERROR_UNKNOWN (%d)", uint32(r))
	}
}

// ResultToError converts CUresult to Go error. Returns nil on CUDA_SUCCESS.
func ResultToError(res CUresult) error {
	if res == CUDA_SUCCESS {
		return nil
	}
	return res
}
